r=range(10)
print(r)
print(list(r))
a=range(1,10)
print(a)
print(list(a))
z=range(2,10,2)
print(z)
print(list(z))
print(10 in z)
print(10 not in z)
print(8 in z)
print(8 not in z)
w=range(2,100,4)
print(list(w))